replicaCount: 1

image:
  repository: ghcr.io/kyenzo/unleash-devops-home-exercise/node-s3-check
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: LoadBalancer
  port: 80

resources: {}

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

# ingress:
#   enabled: true
#   hosts:
#     - host: aaba41a6d356c401680058176d35d045-1367770135.eu-west-1.elb.amazonaws.com
#       paths:
#         - /
#         - /check-file

