name: CI Pipeline

on:
  push:
    branches:
      - master
      - evgeni-cicd-pipeline

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}/node-s3-check:latest .

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Docker image to GitHub Container Registry
        run: docker push ghcr.io/${{ github.repository }}/node-s3-check:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code  # Add this step to access the Helm chart
        uses: actions/checkout@v2
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --name evgeni-eks-cluster --region eu-west-1

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Deploy with Helm
        run: |
          helm upgrade --install node-s3-check helm-charts/file-checker \
            --namespace file-checker \
            --create-namespace \
            --set image.repository=ghcr.io/${{ github.repository }}/node-s3-check \
            --set image.tag=latest \
            --set image.pullPolicy=Always \
            --set hpa.enabled=true \
            --set hpa.minReplicas=2 \
            --set hpa.maxReplicas=10 \
            --set hpa.targetCPUUtilizationPercentage=50

